### ISSUE TITLE
What files do I need for flashing a OnePlus5T?

### ISSUE THREAD

**Issue by twhp-electronic** [seppzer0/s0nh_kernel#2]
Hello!

I want to flash a OnePlus5T with a new Kernel + LinageOS + Nethunter.
Is the file s0nh-dumplinger-pa-4.4.302-0.3.2.zip only for the OnePlus5 or also for the OnePlus5T?

As OP5 is dumpling and OP5T is cheeseburger I guess you made dumplinger out of them??!

**Comment by seppzer0** [comment]
Yes

**Comment by seppzer0** [comment]
The kernel build you want is s0nh-dumplinger-los-4.4.302-0.3.2.zip .

**Comment by twhp-electronic** [comment]
Even when I normally use Magisk?

Okay... I already installed the other one... but there WLAN was not working and an Error appeared:
 
Android-System
There is a internal problem with this device. Please call your manufacturer.

**Comment by twhp-electronic** [comment]
That I used the wrong kernel absolutely was the problem... :-(
Whished I was able to create my own kernel... Had a lot of attempts... but never managed to build my own...

Best wishes.
